import os
import unittest

import pangea.exceptions as pe
import pydantic
from pangea import PangeaConfig
from pangea.response import ResponseStatus
from pangea.services import Redact


class TestRedact(unittest.TestCase):
    def setUp(self):
        token = os.getenv("PANGEA_INTEGRATION_TOKEN")
        domain = os.getenv("PANGEA_INTEGRATION_DOMAIN")
        config = PangeaConfig(domain=domain)
        self.redact = Redact(token, config=config)

    def test_redact(self):
        text = "Jenny Jenny... 415-867-5309"
        expected = "<PERSON>... <PHONE_NUMBER>"

        response = self.redact.redact(text=text)
        self.assertEqual(response.status, ResponseStatus.SUCCESS)
        self.assertEqual(response.result.redacted_text, expected)

    def test_redact_structured(self):
        data = {"phone": "415-867-5309"}
        expected = {"phone": "<PHONE_NUMBER>"}

        response = self.redact.redact_structured(data=data)
        self.assertEqual(response.status, ResponseStatus.SUCCESS)
        self.assertEqual(response.result.redacted_data, expected)

    # call plain redact with structured data, should throw a 400
    def test_redact_with_structured_data(self):
        data = {"phone": "415-867-5309"}

        with self.assertRaises(pydantic.ValidationError):
            self.redact.redact(text=data)  # type: ignore

    def test_redact_with_bad_auth_token(self):
        token = "notarealtoken"
        domain = os.getenv("PANGEA_INTEGRATION_DOMAIN")
        config = PangeaConfig(domain=domain)

        badredact = Redact(token, config=config)

        text = "Jenny Jenny... 415-867-5309"

        with self.assertRaises(pe.UnauthorizedException):
            badredact.redact(text=text)
